### ISSUE TITLE
ESP-IDF C++

### ISSUE THREAD

**Issue by nickypeh** [jamieparkinson/ESP32-MAX31865#1]
Hi, 
I am quite new to the esp32 idf. As your library is in C++, somehow when i include in my components and then include the header file in my main.c file. It failed to compile. 

Is there any special ways to include the C++ components ?

**Comment by jamieparkinson** [comment]
Sorry that I missed this - turn out I wasn't being notified for conversations on my own repo!

If you're still interested, and just for posterity, you're right that you won't be able to include a C++ header in your C sources. 

You could write a wrapper for the functions that you want, where the wrapping function takes a pointer to the class instance as well as the required arguments. Because I've used `enum class`es you'd also need to wrap those - it's a bit of a pain 😞. An example of this sort of wrapper is [here](https://www.teddy.ch/c++_library_in_c/).
